### ISSUE TITLE
Exception retrieving user information

### ISSUE THREAD

**Issue by daryllukas** [sroutier/eloquent-ldap#1]
Hey,
I have succesfully installed this package. However, I'm getting the following error (in logs) when trying to authenticate to my LDAP server.

`Exception retrieving user information: Bind to Active Directory failed. Check the login credentials and/or server details. AD said: No such object`

And on my browser:
![screenshot from 2015-08-14 16 04 21](https://cloud.githubusercontent.com/assets/1014489/9275568/31d4bc3e-429e-11e5-97ed-9597d6e7be05.png)

What does this mean? Kindly note that I use a user_filter on my LDAP server. I noticed there was no way to set this.

Please help.

**Comment by sroutier** [comment]
Hey there,

Can you show or explain how you are setting and using "user_filter". Careful not to paste any passwords.
/s

**Comment by daryllukas** [comment]
Hi,

Thanks for the quick response.
I normally set the "user_filter" (or user object filter) setting to something like this (this code is from another project, not a laravel one):

`user_filter: '(objectClass=inetOrgPerson)(objectClass=posixAccount)(uid=%u)'`

However, I'm wondering how to do this when using this package.

**Comment by sroutier** [comment]
Yeah that would be useful but I do not think that it can be done with the current version of the underlying library used (ADLDAP2 v4.x), I looked into it and the filter is set to:

```
"(&(objectCategory=person)(samaccountname=username))"
```

There is no method to alter it, however, the ADLDAP2 project released version 5.0 a couple of weeks ago. I will have a look at upgrading.

I do not see how the LDAP bind error that you are getting is related to the user_filter. Are you still getting the original error? Did you double check the configuration?

**Comment by sroutier** [comment]
@daryllukas, Just completed upgrading the underlying library and implementing the `user_filter`. Please give it a try when you have a few minutes.
Thanks.
