### ISSUE TITLE
Exception retrieving user information: Undefined variable: username  

### ISSUE THREAD

**Issue by yazir-rizki** [sroutier/eloquent-ldap#5]
I have tried these configuration using Laravel 5.1 enterprise starter kit:

http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/

Server: ldap.forumsys.com  
Port: 389

Bind DN: cn=read-only-admin,dc=example,dc=com
Bind Password: password

All user passwords are password.

You may also bind to individual Users (uid) or the two Groups (ou) that include:

ou=mathematicians,dc=example,dc=com  =>
riemann
gauss
euler
euclid

ou=scientists,dc=example,dc=com   =>
einstein
newton
galieleo
tesla

so the configuration is like this

LDAP.ENABLED=true
LDAP.CREATE_ACCOUNTS=true
LDAP.REPLICATE_GROUP_MEMBERSHIP=true
LDAP.RESYNC_ON_LOGIN=true
LDAP.GROUP_MODEL=App\Models\Role
LDAP.LABEL_INTERNAL=internal
LDAP.LABEL_LDAP=ldap
LDAP.ACCOUNT_SUFFIX=
LDAP.BASE_DN=dc=example,dc=com
LDAP.SERVER=ldap.forumsys.com
LDAP.PORT=389
LDAP.USER_NAME=cn=read-only-admin,dc=example,dc=com
LDAP.PASSWORD=password
LDAP.RETURN_REAL_PRIMARY_GROUP=true
LDAP.SECURED=false
LDAP.SECURED_PORT=636
LDAP.RECURSIVE_GROUPS=true
LDAP.SSO=false
LDAP.USERNAME_FIELD=samaccountname
LDAP.EMAIL_FIELD=userprincipalname
LDAP.FIRST_NAME_FIELD=givenname
LDAP.LAST_NAME_FIELD=sn
LDAP.USER_FILTER=(&(objectcategory=person)(samaccountname=%username))

But I cant login, and log debugbar said 

development.error : Exception retrieving user information: Undefined variable: username  

I try using other method by LDAP Admin, and it works charm like this screenshot

![ldap](https://cloud.githubusercontent.com/assets/20676467/18652724/f2a6b582-7efe-11e6-988b-1ff68482a111.PNG)

Can you help me to solve this?

**Comment by sroutier** [comment]
Hello @yazir-reinovasi,

Just wanted to drop a quick note to let you know that I am looking into this. I have it almost fixed, please hang on.

Will be back soon with good news I hope.
/s

**Comment by yazir-rizki** [comment]
okay thanks :)

**Comment by sroutier** [comment]
Hello @yazir-reinovasi,

I just submitted a patch to both this module and the parent project LESK that should at least allow you to authenticate your users against an LDAP server. I tested with the OpenLDAP server that you pointed me to above. Please try it and let me know.

Currently the group membership of the user is not synchronized or updated upon login,  as the behaviour is different between LDAP and MSAD, but I will look at that next and try to fix it.

There are a couple of configuration options that must be changed so make sure to check the updated README and let me know if you have any problems.

Thanks.
/S

**Comment by yazir-rizki** [comment]
I use  Laravel 5.1 enterprise starter kit, should I update from there or manually?

thanks a lot for your support

**Comment by sroutier** [comment]
Update LESK with a `git pull` as I did not yet make a tag release.
Update the eloquent-ldap package with a `composer update sroutier/eloquent-ldap` command. Make sure that you get the latest tag `0.1.8`.

That should do it. Let me know if you have any trouble.
/s

**Comment by yazir-rizki** [comment]
Thx sroutier, 
we have progress for this :+1: 

but we still cant login, our code : 

LDAP.ENABLED=true
LDAP.DEBUG=false
LDAP.SERVER_TYPE=LDAP
LDAP.CREATE_ACCOUNTS=true
LDAP.REPLICATE_GROUP_MEMBERSHIP=false
LDAP.RESYNC_ON_LOGIN=false
LDAP.GROUP_MODEL=App\Models\Role
LDAP.LABEL_INTERNAL=internal
LDAP.LABEL_LDAP=ldap
LDAP.ACCOUNT_SUFFIX=@ldap.forumsys.com
LDAP.BASE_DN=dc=example,dc=com
LDAP.SERVER=ldap.forumsys.com
LDAP.PORT=389
LDAP.USER_NAME=dc=example,dc=com
LDAP.PASSWORD=password
LDAP.RETURN_REAL_PRIMARY_GROUP=true
LDAP.SECURED=false
LDAP.SECURED_PORT=636
LDAP.RECURSIVE_GROUPS=true
LDAP.SSO=false
LDAP.USERNAME_FIELD=uid
LDAP.EMAIL_FIELD=mail
LDAP.FIRST_NAME_FIELD=cn
LDAP.LAST_NAME_FIELD=sn
LDAP.USER_FILTER=(&(objectClass=person)(uid=%username))

is there any mistake?

because I cant login using these http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/ credential

**Comment by sroutier** [comment]
Hello @yazir-reinovasi,

I did a diff between your config and the sample provided in the readme and you have 3 fields that need correction:

```
LDAP.ACCOUNT_SUFFIX=
LDAP.USER_NAME=cn=read-only-admin,dc=example,dc=com
LDAP.FIRST_NAME_FIELD=
```

Try that and let me know.
/s
